name: deploy dev

on:
  push:
    branches:
      - fix-deployment
  workflow_dispatch:
    
env:
  REPOSITORY: 'tangotew/afi-load-board-app'

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && contains(github.ref, 'fix-deployment')) || github.event_name == 'workflow_dispatch' 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ORG_GITHUB_TOKEN }}

    - name: Extract tag based on environment from manifest.yaml
      if: github.ref == 'refs/heads/fix-deployment' && github.event_name == 'workflow_dispatch'
      run: |
        TAG=$(grep -A1 "dev:" manifest.yaml | grep 'version:' | awk '{print $2}')
        echo "RELEASE_TAG=${{env.REPOSITORY}}:${TAG}" >> $GITHUB_ENV
        echo "TAG=$TAG" >> $GITHUB_ENV
    
    - name: Use SHA for tag if not main
      if: github.event_name == 'push' && github.ref != 'refs/heads/fix-deployment'
      run: echo "RELEASE_TAG=${{ env.REPOSITORY}}:${{ github.sha }}" >> $GITHUB_ENV
      
    - name: Set Git Config
      if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/fix-deployment'
      run: |
        git config --global --replace-all user.email 'GitHub Action'
        git config --global --replace-all user.name 'actions@github.com'
    
    - name: Check if Git tag exists
      if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/fix-deployment'
      id: check_tag
      run: |
        TAG_NAME=${{ env.TAG }}
        TAG_EXISTS=$(git ls-remote --tags origin refs/tags/$TAG_NAME)
        if [[ -z "$TAG_EXISTS" ]]; then
          echo "Tag does not exist"
          echo "tag-exists=false"  >> "$GITHUB_OUTPUT"
        else
          echo "Tag exists"
          echo "tag-exists=true" >> "$GITHUB_OUTPUT"
        fi
      continue-on-error: true

    - name: Debug tag-exists
      run: |
        echo "Tag Exists: ${{ steps.check_tag.outputs.tag-exists }}"

    - name: Push Git Tag
      if: "${{ steps.check_tag.outputs.tag-exists == 'false' && github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/fix-deployment' }}"
      run: |
        git tag -a ${{ env.TAG }} -m "Release ${{ env.TAG }}"
        git push --no-verify origin refs/tags/${{ env.TAG }}

    - name: Create PreRelease
      if: "${{ steps.check_tag.outputs.tag-exists == 'false' && github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/fix-deployment' }}"
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.ORG_GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d '{
            "tag_name": "'${{ env.TAG }}'",
            "name": "Prerelease '${{ env.TAG }}'",
            "body": "Changes in this Release\n- Added Automation for docker build and push\n- Added autodeployment pipeline",
            "draft": false,
            "prerelease": true
          }'
    outputs:
      TAG: "${{env.RELEASE_TAG}}"
      TAG_EXISTS: "${{ steps.check_tag.outputs.tag-exists }}"

  build_and_push:
    needs: [prepare]
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/fix-deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine tag for image
        run: echo "RELEASE_TAG=${{needs.prepare.outputs.TAG}}" >> $GITHUB_ENV

      - name: Display tag
        run: echo "tag=${{env.RELEASE_TAG}}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Try to pull Docker image
        id: docker_pull
        continue-on-error: true # Continue even if the pull fails
        run: |
          docker pull ${{env.RELEASE_TAG}} && echo "PULL_SUCCEEDED=true" >> $GITHUB_ENV || echo "PULL_SUCCEEDED=false" >> $GITHUB_ENV

      - name: Build and push Docker image
        if: env.PULL_SUCCEEDED == 'false'
        run: |
          DOCKER_IMAGE=${{ env.RELEASE_TAG }}
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
      
      - name: Display tag in the Summary
        run: echo "::notice title=Pushing tag::${{env.RELEASE_TAG}}"

    outputs:
      image_digest: ${{ env.RELEASE_TAG }}

  checkout_tag:
    needs: [prepare, build_and_push]
    runs-on: ubuntu-latest
    steps:
      - name: Display Tag
        run: echo "RELEASE_TAG=${{needs.prepare.outputs.TAG}}" >> $GITHUB_ENV
        
  deploy:
    needs: [build_and_push]
    if: github.event_name != 'workflow_dispatch' && github.ref != 'refs/heads/fix-deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Display Tag
        run: echo "${{needs.build_and_push.outputs.image_digest}}"

      - name: Get Tag
        run: |
          echo "RELEASE_TAG=${{ needs.build_and_push.outputs.image_digest }}" >> $GITHUB_ENV
          echo "Retrieved the docker image tag: ${{ env.RELEASE_TAG }}"

      # Step to check if doctl is already installed
      - name: Check if doctl is installed
        run: |
          echo "checking if doctl is installed"
          if command -v doctl &> /dev/null; then
            echo "doctl is already installed"
            doctl version
          else
            echo "doctl is not installed"
          fi

      # Step to install doctl
      - name: Install doctl
        run: |
          if ! command -v doctl &> /dev/null; then
            curl -s https://api.github.com/repos/digitalocean/doctl/releases/latest \
            | grep "browser_download_url.*linux-amd64.tar.gz" \
            | cut -d '"' -f 4 \
            | wget -qi -
            tar xf doctl-*-linux-amd64.tar.gz
            sudo mv doctl /usr/local/bin
            doctl version
          fi

      # Step to authenticate doctl
      - name: Authenticate doctl
        run: |
          echo "authenticating doctl"
          doctl auth init --access-token ${{ secrets.DIGITALOCEAN_API_TOKEN }}

      # Step to check if a Droplet with the name 'afi-load-board' already exists
      - name: Check for existing Droplet
        run: |
          EXISTING_DROPLET_ID=$(doctl compute droplet list --format ID,Name --no-header | awk '/afi-load-board/ {print $1}')
          if [ -n "$EXISTING_DROPLET_ID" ]; then
            echo "Droplet with name afi-load-board already exists with ID: $EXISTING_DROPLET_ID"
            echo "DROPLET_ID=$EXISTING_DROPLET_ID" >> $GITHUB_ENV
          else
            echo "No existing Droplet with name afi-load-board found."
          fi


      - name: Get SSH Key Fingerprint
        run: |
          SSH_FINGERPRINT=$(doctl compute ssh-key list --format FingerPrint --no-header)
          echo "SSH_FINGERPRINT=$SSH_FINGERPRINT" >> $GITHUB_ENV

      - name: Create a Droplet
        if: env.DROPLET_ID == ''
        env:
          DROPLET_SSH_KEY: ${{ env.SSH_FINGERPRINT }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          echo "$DROPLET_SSH_KEY" > droplet_ssh_key
          chmod 600 droplet_ssh_key

          DROPLET_ID=$(doctl compute droplet create afi-load-board --size s-1vcpu-1gb --image ubuntu-20-04-x64 --region sfo3 --ssh-keys $SSH_FINGERPRINT --format ID --no-header --wait)
          echo "Droplet ID: $DROPLET_ID"
          echo "DROPLET_ID=$DROPLET_ID" >> $GITHUB_ENV

      - name: Get Droplet IP
        run: |
          DROPLET_IP=$(doctl compute droplet get $DROPLET_ID --format PublicIPv4 --no-header)
          echo "DROPLET_IP=$DROPLET_IP" >> $GITHUB_ENV

      - name: Setup SSH key for Droplet
        env:
          DROPLET_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$DROPLET_SSH_PRIVATE_KEY" > droplet_private_ssh_key
          chmod 600 droplet_private_ssh_key 

      - name: Install Docker on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no -i droplet_private_ssh_key root@$DROPLET_IP "sudo apt update && apt install -y docker.io"

      - name: Check if Docker Network Exists on Droplet
        run: |
          EXISTING_NETWORK=$(ssh -o StrictHostKeyChecking=no -i droplet_private_ssh_key root@$DROPLET_IP "docker network ls --filter name=afi-loadbaord-network -q")
          echo "EXISTING_NETWORK=$EXISTING_NETWORK" >> $GITHUB_ENV

      - name: Create Docker Network on Droplet
        run: |
          if [ -z "$EXISTING_NETWORK" ]; then
            ssh -o StrictHostKeyChecking=no -i droplet_private_ssh_key root@$DROPLET_IP "docker network create afi-loadbaord-network"
          else
            echo "Docker network afi-loadbaord-network already exists. Skipping creation."
          fi

      # - name: Create Docker Network on Droplet
      #   run: |
      #     echo "creating docker network on droplet"
      #     ssh -o StrictHostKeyChecking=no -i droplet_private_ssh_key root@$DROPLET_IP "docker network create afi-loadbaord-network || true"

      - name: Deploy to Droplet
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
        run: |
          # Run commands on the remote server
          echo "Deploying image $RELEASE_TAG in the Droplet VM"
          ssh -o StrictHostKeyChecking=no -i droplet_private_ssh_key root@$DROPLET_IP << EOF
            echo "RELEASE_TAG is: $RELEASE_TAG"
            if [ -z "$RELEASE_TAG" ]; then
              echo "RELEASE_TAG is not set. Exiting."
              exit 1
            fi
            docker pull $RELEASE_TAG
            docker run -d -p 80:300 --network afi-loadbaord-network $RELEASE_TAG
          EOF


            
            
            
                
