name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create release tag
      if: github.ref != 'refs/heads/master'
      run: echo "RELEASE_TAG=$(date '+%Y%m%d.%H%M%S')" >> $GITHUB_ENV

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: docker-user/docker-repo:$RELEASE_TAG
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
